language: node_js
node_js:
- '0.10'
env:
  global:
    - secure: "TeNSTzUV1a7HKl3TtnVH81GhH7Eh70NVLWkUSFD3NnFjAQYZ11OPvA5hod0TwIV5y2ZPmEqB3zFYZ2CcoyYuFyMPl4TeVSRvMjyxUWCrVZg2Nd7G+xGH0pLGZjJRb0IL/+PjQWisxkbkR9eUBe664nsR1GWP71CwQpEZQ1SRbEY="
    - secure: "DSsHQ+7nbXg+CtHf39Cenu2GeZrLq6Wme0vq3UE0yWLCD2fMQBpLSRbTLJJNxWLIM1ev6YsBYL11jFNq/X3uWaxvGK8eDg+Ez54SlwFfwACAzhUzf6l31ZhO9v700SvbHj2O2Ty6crqIch6aY2JJUicnA0ACabCP92q7JuRUKmQ="
    - secure: "OKjFqh8Icg3T6mDJq/f4GFQnxiVCCJPOlRH6cnD66xl62qqdlwvE2pbGp38UB/EtrpR6KiplSkZXNYAy5vYE6m8YdvyrLX8IwxtYJ4T+XudzHYXnbvVHrF2VwqnlPfVU3lCJvcdP0vcFeiKrzhfJB/u1gJHaWGYqhYc26M0dHto="