language: node_js
node_js:
- '0.10'
env:
  secure: bO81WBsOe+VoCgJTfjC1kkn6MLbQW+7Vcxf7xjQtzAVW9AXFyfpy/PWZhWcyMDexWhCLU+b/v7wQht10tfyTxiTEYY4UZRQH5d03BYWXXpqLPpoqiflZzXdjpVhHZRU9QxipR+Y29mfw4BQyYf79D8F6jvqNvgAD8zYPdjPEihA=
